// 🐶 SoyPerritoProProYT-Bed · puente Web ↔ Bedrock real + Modo Amigos
const express=require('express');const http=require('http');const WebSocket=require('ws');const {createBot}=require('prismarine-bedrock');const {Vec3}=require('vec3');
const app=express(),server=http.createServer(app),wss=new WebSocket.Server({server});
app.get('/',(_q,r)=>r.type('html').send('<h1>🐶 SoyPerritoProProYT-Bed</h1><p>🟢 Relay Bedrock + Modo Amigos online.</p>'));app.get('/health',(_q,r)=>r.json({ok:true,service:'SoyPerritoProProYT-Bed',version:5}));
const online=new Map(),friends=new Map();
function send(ws,type,data={}){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type,...data}))}function broadcast(type,data={}){for(const ws of online.values())send(ws,type,data)}function listFriends(name){return [...(friends.get(name)||[])].map(n=>({name:n,online:online.has(n)}))}
function safe(v){try{return JSON.parse(JSON.stringify(v,(_k,x)=>typeof x==='bigint'?Number(x):x))}catch{return null}}function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
async function snapshot(bot,ws,r=10,v=8){if(!bot?.entity?.position&&!bot?.self?.position)return;const p=bot.entity?.position||bot.self?.position,cx=Math.floor(p.x),cy=Math.floor(p.y),cz=Math.floor(p.z),blocks=[];for(let x=cx-r;x<=cx+r;x++)for(let z=cz-r;z<=cz+r;z++)for(let y=Math.max(-64,cy-v);y<=Math.min(cy+v,319);y++){try{const b=bot.blockAt(new Vec3(x,y,z));if(b&&b.name&&b.name!=='air')blocks.push({x,y,z,name:b.name,stateId:b.stateId??null})}catch{}}send(ws,'world_snapshot',{center:{x:cx,y:cy,z:cz},blocks,blockCount:blocks.length,dimension:bot.game?.dimension??0,gameMode:bot.game?.gameMode??0})}
function inv(bot){return bot.inventory?(bot.inventory.slots||[]).map((i,slot)=>i?{slot,name:i.name,displayName:i.displayName,count:i.count,stackId:i.stackId??null}:null):[]}
function players(bot){const out=[],ps=bot.players instanceof Map?bot.players:new Map(Object.entries(bot.players||{}));for(const[id,p]of ps)out.push({runtimeId:String(id),username:p.username||p.name||'Jugador',position:p.position?safe(p.position):null,yaw:num(p.yaw),pitch:num(p.pitch)});return out}

wss.on('connection',ws=>{let bot=null,syncing=false,lastSnapshot=0;const controls={forward:false,back:false,left:false,right:false,jump:false,sprint:false,sneak:false,swim:false};let username='';
const apply=()=>{if(!bot)return;for(const[k,v]of Object.entries(controls))try{bot.setControlState(k,v)}catch{}};const timer=setInterval(apply,50);const bind=(e,f)=>{try{bot.on(e,f)}catch{}};
async function snap(force=false){if(!bot||syncing)return;const now=Date.now();if(!force&&now-lastSnapshot<1400)return;lastSnapshot=now;syncing=true;try{await snapshot(bot,ws)}finally{syncing=false}}
ws.on('message',async raw=>{try{const m=JSON.parse(raw.toString());
if(m.type==='presence_join'){username=String(m.username||'').trim().slice(0,16);if(!username)return send(ws,'error',{message:'Nombre requerido.'});online.set(username,ws);if(!friends.has(username))friends.set(username,new Set());send(ws,'presence',{name:username,online:true,friends:listFriends(username)});broadcast('presence_update',{name:username,online:true});return}
if(m.type==='friends_list'){send(ws,'friends',{records:listFriends(username)});return}
if(m.type==='friend_add'){const target=String(m.name||'').trim().slice(0,16);if(!username||!target)return;const set=friends.get(username)||new Set();set.add(target);friends.set(username,set);send(ws,'friends',{records:listFriends(username)});if(online.has(target))send(online.get(target),'friend_request',{from:username});return}
if(m.type==='friend_remove'){const target=String(m.name||'').trim();friends.get(username)?.delete(target);return send(ws,'friends',{records:listFriends(username)})}
if(m.type==='ping')return send(ws,'pong',{time:Date.now()});
if(m.type==='connect'){const host=String(m.host||'').trim(),port=Number(m.port||19132),user=String(m.username||username||'SoyPerrito').trim().slice(0,16)||'SoyPerrito',version=String(m.version||'').trim()||undefined;if(!host||!Number.isInteger(port)||port<1||port>65535)return send(ws,'error',{message:'Host o puerto no válido.'});username=user;try{bot?.disconnect('Nueva conexión')}catch{};Object.keys(controls).forEach(k=>controls[k]=false);send(ws,'connecting',{host,port,username,version:version||'auto'});try{bot=createBot({host,port,username,offline:m.offline!==false,...(version?{version}:{}),loggingEnabled:false,worldDecodeEnabled:true,physicsEnabled:true,chunkRadius:6})}catch(e){return send(ws,'error',{message:e.message||String(e)})}bind('join',()=>send(ws,'connected',{host,port,username,version:bot.version}));bind('spawn',async()=>{send(ws,'spawn',{position:safe(bot.entity?.position||bot.self?.position),game:safe(bot.game)});send(ws,'players',{records:players(bot)});send(ws,'inventory',{slots:inv(bot)});await snap(true)});bind('health',()=>send(ws,'health',{health:bot.playerState?.health??bot.entity?.health??null}));bind('chat',d=>send(ws,'chat',{source:d.username||d.source_name||d.sender||'',message:d.message||String(d)}));bind('physicsTick',()=>{apply();const p=bot.entity?.position||bot.self?.position;if(p)send(ws,'self',{position:safe(p),yaw:num(bot.entity?.yaw||bot.self?.yaw),pitch:num(bot.entity?.pitch||bot.self?.pitch)})});bind('diggingCompleted',d=>{send(ws,'block_update',{action:'break',block:safe(d.block)});snap(true)});bind('close',r=>send(ws,'disconnected',{reason:String(r||'Servidor desconectado')}));bind('error',e=>send(ws,'error',{message:e?.message||String(e)}));return}
if(!bot)return send(ws,'error',{message:'Conecta primero a un servidor.'});if(m.type==='controls'){for(const k of Object.keys(controls))if(typeof m[k]==='boolean')controls[k]=m[k];apply();return}if(m.type==='look'){try{await bot.look(num(m.yaw)*Math.PI/180,num(m.pitch)*Math.PI/180,true)}catch(e){send(ws,'error',{message:e.message||String(e)})}return}if(m.type==='chat'){const t=String(m.message||'').trim().slice(0,256);if(t)try{bot.chat(t)}catch(e){send(ws,'error',{message:e.message||String(e)})}return}if(m.type==='sync_world')return snap(true);if(m.type==='inventory')return send(ws,'inventory',{slots:inv(bot)});if(m.type==='break'){try{const b=bot.blockAt(new Vec3(Math.floor(num(m.x)),Math.floor(num(m.y)),Math.floor(num(m.z))));if(!b||b.name==='air')return send(ws,'action_error',{action:'break',message:'Bloque no cargado.'});await bot.dig(b,true);await snap(true)}catch(e){send(ws,'action_error',{action:'break',message:e.message||String(e)})}return}if(m.type==='place'){try{const b=bot.blockAt(new Vec3(Math.floor(num(m.x)),Math.floor(num(m.y)),Math.floor(num(m.z))));await bot.placeBlock(b,new Vec3(num(m.fx),num(m.fy),num(m.fz)),{waitForUpdate:true});await snap(true)}catch(e){send(ws,'action_error',{action:'place',message:e.message||String(e)})}return}if(m.type==='disconnect'){try{bot.disconnect('Desconectado')}catch{}bot=null;send(ws,'disconnected',{reason:'Desconectado'})}
}catch(e){send(ws,'error',{message:e.message||String(e)})}});ws.on('close',()=>{clearInterval(timer);if(username&&online.get(username)===ws){online.delete(username);broadcast('presence_update',{name:username,online:false})}try{bot?.disconnect('WebSocket cerrado')}catch{}})});
const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`🐶 SoyPerritoProProYT-Bed listening on ${PORT}`));
